### ISSUE TITLE
parser error on #echo

### ISSUE THREAD

**Issue by DogRiley** [joemcbride/outlander-osx#77] opened 2016-08-28 15:17 UTC
Seems when there is: (including regex to demonstrate boundaries, they are not in the code)
put #echo This is my echo text\n
put #echo This is line 2 of my text\n

The parser works correctly.  But when the #echo line ends in 1 or more spaces the parser includes the next line as #echo text including the 'put #echo' portion
put #echo This is my echo text\s+\n
put #echo This is line 2 of my text\n

Output of the second set generates:
This is my echo text
put #echo This is line 2 of my text

**Comment by joemcbride** [comment] 2016-08-28 17:15
Writing a simple script to reproduce, it does work as intended.

```
put #echo This is my echo text    
put #echo This is line 2 of my text
```

Are you seeing that within an `if` block per chance?

**Comment by DogRiley** [comment] 2016-08-28 23:21
No, was in a big text block, My example was not tested, apologies, I will
do that next time. I just tested the section that was failing, as stand
alone code it works... it must be an error earlier in the script that is
causing the behavior...

I am working on translating an existing script (progressive steal) to
Outlander.  As part of the translation I am finding that generally cleaning
up trailing spaces reduces parsing errors in variable assignment and echo
text.

Questions:
is put #echo / or echo preferred from within the script?
is there a limit on the size/length of a script file or number of variables?
would love the have include working :)

**Comment by joemcbride** [comment] 2016-08-28 23:36
`#echo` gives you a few more features vs. `echo`.

`echo` - does just that - echos the the text
`#echo` - you can target a specific window and add colors

`#echo [>targetWindow] [color[,backgroundcolor]] <text>`

Right now, any script over about 1000 lines will give Outlander trouble.

**Comment by DogRiley** [comment] 2016-08-29 00:19
Oh, and concatenation of variables that hold string values?

Are these supported or is there a different structure?:

var newvar textword%counter
var anothernewvar %var1textword%counter

**Comment by joemcbride** [comment] 2016-09-23 06:47
Going to close this.  Let me know if there was something different than the variable issue that was fixed.

**Closed by joemcbride** 2016-09-23 06:47 UTC
