### ISSUE TITLE
Allow variables in actions

### ISSUE THREAD

**Issue by HanryuDR** [joemcbride/outlander-osx#121] opened 2017-03-19 02:15 UTC
I'd like for something like this to work so I can adjust actions with passed variables

var item %0
action var page $1 when (\d+) -- a deed for an? %item

----

[Script 'unregister' completed after 28.52 seconds total run time]
[Starting 'unregister' at 10:10 PM]
[unregister(2)]: debuglevel 5
[unregister(4)]: if - 2 >= 1 = true
[unregister(4)]: goto start 
[unregister(14)]: passing label start
[unregister(15)]: setvariable item bronze-alloy ingot
[unregister(16)]: action var page $1 when (\d+) -- a deed for an? %item
[unregister(18)]: gosub get deed register
[unregister(51)]: passing label get
[unregister(52)]: setvariable item deed register

**Comment by joemcbride** [comment] 2017-03-19 16:26
This is basically a duplicate of #108 .

**Comment by joemcbride** [comment] 2017-04-21 17:26
Closing in favor of #108

**Closed by joemcbride** 2017-04-21 17:26 UTC
Labels: duplicate
