### ISSUE TITLE
eval VAR replacere("%VAR", not working properly

### ISSUE THREAD

**Issue by HanryuDR** [joemcbride/outlander-osx#106] opened 2017-02-03 15:13 UTC
eval fullcombo replacere("%fullcombo", "( and an? |, an? )", "\|")
that line does not update the variable full combo

 eval temp replacere("%fullcombo", "( and an? |, an? )", "\|")
 var fullcombo %temp

that works just fine

**Comment by joemcbride** [comment] 2017-03-18 05:30
Looks like this is a dupe of #93 - just didn't realize what the issue was.

**Comment by joemcbride** [comment] 2017-04-21 18:08
Fixed in new script engine

**Closed by joemcbride** 2017-04-21 18:08 UTC
Labels: bug
