### ISSUE TITLE
Having problem with infinite loops message setting up sounds for 0.11.1 using phrases separated by a |

### ISSUE THREAD

**Issue by tbgg** [joemcbride/outlander-osx#120] opened 2017-03-18 07:15 UTC
I have certain phrases that I want to both highlight using the same color and play the same sound for.  The biggest example of this that comes to mind for me on this is the messages indicating danger in both mining and lumberjacking. 

I previously added the mining messages, but not the ones for lumberjacking.  When I try to create those now, and I enter a | to separate out the different messages I want to handle the same way, I get the infinite loop message (the second of the 2 you asked me about earlier) if the | is the last character.  This message hangs me.  I can't get control of the application again to change ANYTHING to stop this message - I HAVE TO Force Quit, and that's really annoying, because it means I lose all of the sounds I just configured.  Is there a way I can get control again so I can change what it's complaining about - presumably remove the |?  Moving forward, I know I can enter the two phrases and then put the | in afterward, but that just seems really awkward, and I'm not sure how likely I am to REMEMBER to do that.

Thanks!

**Comment by joemcbride** [comment] 2017-03-18 07:19
You can manually edit the highlights.cfg file in any text editor.  Can you post the exact contents that is causing the error you're seeing?

**Comment by joemcbride** [comment] 2017-03-18 07:24
Also, if you close the preferences window or move to a different tab it will auto save the changes to disk.

So I'm a little confused - I'm guessing you're editing the highlight while the game is running, are typing in the regex and the game hangs because it's only a partial regex?  If possible, it would be very helpful if you could record your screen if you can reproduce this.

**Comment by tbgg** [comment] 2017-03-18 07:31
Steps to trigger error:  
Start new highlight
Enter color #FF8800
For Highlight, enter You notice an unusual smell drifting through the area.|
Move to copy in next phrase, i.e. A bitter smell seeps into the air.
Before I can return to add this to the Highlight field, BOOM, hung

Are there utilities you can recommend for capturing what I'm doing?  I know how to take screen captures, but it sounds like you're asking for a recording, and while I've used special applications to do that before, those were through work and I don't have anything like on my Mac.  Not unless there's some built-in utility I don't know about.

**Comment by joemcbride** [comment] 2017-03-18 07:35
I can probably reproduce it with that. You can record you're screen with QuickTime. https://support.apple.com/kb/ph5882?locale=en_US

**Comment by joemcbride** [comment] 2017-03-19 16:32
This should be fixed now!  https://github.com/joemcbride/outlander-osx/releases/tag/v0.11.2

**Closed by joemcbride** 2017-03-19 16:32 UTC
